function ContactSection() {
  return (
    <section
      id="contact"
      className="flex min-h-[400px] snap-center flex-col items-center justify-center bg-black p-5"
    >
      <div className="mb-20">
        <p className="mb-3">
          The above Japanese description and products are all generated by
          ChatGPT. <br /> I don't speak any Japanese; this is just a practice
          project!
        </p>
        <p className="text-xl font-bold">Please forgive me 😉</p>
      </div>

      <div>
        <div className="mb-6 flex flex-col items-center justify-center">
          <p className="mb-2 text-center">
            Gsap Motion Effect Reference From{' '}
            <span className="font-semibold underline decoration-2">
              <a href="https://manayerbamate.com/">Mana</a>
            </span>
            <br />
            Ray Marching From{' '}
            <span className="font-semibold underline decoration-2">
              <a href="https://medium.com/@nabilnymansour/ray-marching-in-three-js-66b03e3a6af2">
                Nabil Mansour
              </a>
            </span>
            <br />
            Star Point Shader{' '}
            <span className="font-semibold underline decoration-2">
              <a href="https://threejs-journey.com/">Bruno Simon</a>
            </span>
          </p>

          <p className="font-black">Practice creating those cool shaders! 😍</p>
        </div>

        <div className="flex items-center justify-center">
          <a
            href="https://github.com/YUNI0107"
            target="_blank"
            className="mr-4"
          >
            <div className="flex items-center justify-center">
              <i className="ri-github-fill mr-2 text-3xl"></i>
              <h3 className="text-xl">YUNI0107</h3>
            </div>
          </a>
          <p>2024 - Project</p>
        </div>
      </div>
    </section>
  )
}

export default ContactSection
